hypertrace/attribute-service

- helm/configs/1_event_attributes.conf
Renamed attributes to have better display names
> Better display names for attributes

- attribute-service-api/src/main/proto/org/hypertrace/core/attribute/service/v1/attribute_metadata.proto
- attribute-service-impl/src/main/java/org/hypertrace/core/attribute/service/model/AttributeMetadataModel.java
- attribute-service-impl/src/test/java/org/hypertrace/core/attribute/service/AttributeServiceImplTest.java
- attribute-service-impl/src/test/java/org/hypertrace/core/attribute/service/model/AttributeMetadataModelTest.java
With groupable field, UI will render attribute in group-by widget iff groupable == true
> add groupable field

- helm/Chart.yaml
update config bootstrapper to 0.1.12
> update config bootstrapper to 0.1.12

- attribute-service-client/src/main/java/org/hypertrace/core/attribute/service/client/AttributeServiceClient.java
The new interface will help in resolving the logging issue - https://github.com/hypertrace/hypertrace/issues/89
> adding shutdown interface for gracefully closing channel

- attribute-service-api/src/main/proto/org/hypertrace/core/attribute/service/v1/attribute_metadata.proto
- caching-attribute-service-client/src/main/java/org/hypertrace/core/attribute/service/cachingclient/CachingAttributeClient.java
- caching-attribute-service-client/src/test/java/org/hypertrace/core/attribute/service/cachingclient/CachingAttributeClientTest.java
also required channel for caching client construction
> refactor: add source path to attribute definition

- helm/Chart.yaml
Config bootsrapper helm chart dependency upgrade
> chore: update config bootstrapper to v0.2.0

- .snyk
- attribute-service/build.gradle.kts
No patch available so added the vunerability to be ignored in .snyk file
> fix: snyk fix for ionetty

- .circleci/config.yml
- attribute-service/build.gradle.kts
Update framework version for vulnerability fixes, limit snyk to run on runtime code.
- [n/a] I have added tests that prove my fix is effective or that my feature works
> chore: update vulnerable dependencies

- .github/CODEOWNERS
- .github/workflows/pr-build.yml
Update snyk gh action invocation to use the local dev workspace which matches the expected project path. Also fixed a syntax error in GHA codeowners
> ci: update snyk gh action

- .github/workflows/merge-publish.yml
- .github/workflows/pr-build.yml
- .github/workflows/publish.yml
- uses dockerhub read and publish tokens according to required scope.
> uses read and publish docker env variables according to scope

- .github/CODEOWNERS
- helm/Chart.yaml
This updates config bootstrapper to `0.2.3`, which includes the new space attribute definitions
> chore: updating config bootstrapper and adding codeowner

- README.md
- adds how to run integration test in README
NA
> adds integration test steps in README

- .github/workflows/merge-publish.yml
- .github/workflows/pr-build.yml
- .github/workflows/publish.yml
- Changes `run` to `uses` for using our custom actions.
> fixes typo in PR#61

- attribute-service/build.gradle.kts
Updates the latest version of the service framework in the context of addressing the issue - https://github.com/hypertrace/hypertrace/issues/137 Pl refer discussion on the issue and associated merged PR for further information.
> chore:updates service framework version to address security concern

- .github/workflows/merge-publish.yml
- .github/workflows/pr-test.yml
- adds codecov upload for integration test which was somehow removed during earlier changes. 
- removes unnecessary checkout args from merge-publish.
> fix: codecov for integration test & cleanup merge-publish

- helm/Chart.yaml
- Updating Config-bootstrapper version to add changes from https://github.com/hypertrace/config-bootstrapper/pull/44
NA
> chore: updated config-bootstrapper version

- helm/Chart.yaml
- Updating Config-bootstrapper version to add changes from https://github.com/hypertrace/config-bootstrapper/pull/47
NA
> chore: updates config boostrapper version

- .snyk
- attribute-projection-functions/build.gradle.kts
- attribute-projection-registry/build.gradle.kts
- attribute-service-api/build.gradle.kts
- attribute-service-client/build.gradle.kts
- attribute-service-impl/build.gradle.kts
- attribute-service-tenant-api/build.gradle.kts
- attribute-service/build.gradle.kts
- caching-attribute-service-client/build.gradle.kts
Update vulnerabilities and other deps
UTs
- [N/A] I have added tests that prove my fix is effective or that my feature works
> chore: update dependencies for vulns

- helm/Chart.yaml
Adds in some new attribute defs
> chore: update bootstrapper

- helm/Chart.yaml
updates config bootstrapper version to incorporate changes done to add API trace error count attribute.
> chore: update config bootstrapper for API Trace error count

- helm/Chart.yaml
- updates the config bootstrapper version to latest
> chore: updates the config bootstrapper version deps

- .snyk
- attribute-service-api/build.gradle.kts
- attribute-service-client/build.gradle.kts
- attribute-service-impl/build.gradle.kts
- attribute-service/build.gradle.kts
- caching-attribute-service-client/build.gradle.kts
- helm/Chart.yaml
Updated config bootstrapper version and grpc versions.
> chore : updated config bootstrapper

- attribute-service-impl/build.gradle.kts
- attribute-service/build.gradle.kts
- caching-attribute-service-client/build.gradle.kts
> fix: upgrade vulnerable log4j

- attribute-service/build.gradle.kts
Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.
> chore: update log4j version to 2.17.0

- attribute-projection-functions/build.gradle.kts
- attribute-projection-registry/build.gradle.kts
- attribute-service-api/build.gradle.kts
- attribute-service-client/build.gradle.kts
- attribute-service-impl/build.gradle.kts
- attribute-service-tenant-api/build.gradle.kts
- attribute-service/build.gradle.kts
- caching-attribute-service-client/build.gradle.kts
Upgrade various dependencies
Ran tests, no code changes.
> chore: upgrade dependencies

- attribute-service-impl/build.gradle.kts
- attribute-service-impl/src/test/java/org/hypertrace/core/attribute/service/AttributeServiceImplTest.java
- attribute-service/build.gradle.kts
- Upgrade the document store lib version and fixed the test to handle upgrade of hypertrace-service (ref : https://github.com/hypertrace/hypertrace-service/pull/123#issuecomment-1070371677)
> chore: upgrade document-store version and fixed tests

- .snyk
- attribute-service-api/src/main/proto/org/hypertrace/core/attribute/service/v1/attribute_metadata.proto
- attribute-service/build.gradle.kts
Added new `SENSITIVE_SPAN` scope for sensitive data attributes.
> added new scope

- attribute-service-factory/build.gradle.kts
- attribute-service/build.gradle.kts
Update service framework version
> chore: update service framework version

- attribute-service-factory/build.gradle.kts
- attribute-service/build.gradle.kts
- attribute-service/src/main/java/org/hypertrace/core/attribute/service/AttributeServiceEntry.java
Update framework version and use new server building style.
> chore: update framework version

- attribute-service-factory/build.gradle.kts
- attribute-service-impl/build.gradle.kts
> chore: upgrading doc-store libs

- attribute-service-factory/build.gradle.kts
- attribute-service-impl/build.gradle.kts
Include the fix for the selection clause in document-store - https://github.com/hypertrace/document-store/pull/115
> chore: update doc-store lib version

- attribute-projection-functions/build.gradle.kts
- attribute-projection-functions/src/main/java/org/hypertrace/core/attribute/service/projection/functions/Hash.java
Verified the UUID values generated are same as the older version
> chore: upgrade uuid

- attribute-service-factory/build.gradle.kts
- attribute-service-impl/build.gradle.kts
- Upgrade doc-store for latest fixes
> chore: updating doc-store version to take latest fixes

- helm/Chart.yaml
See https://github.com/hypertrace/config-bootstrapper/pull/83
> chore: update bootstrapper to fix attribute bootstrap

- .github/workflows/codeql-analysis.yml
- .github/workflows/merge-publish.yml
- .github/workflows/pr-build.yml
- .github/workflows/pr-test.yml
- .github/workflows/publish.yml
- attribute-service-api/build.gradle.kts
- attribute-service-client/build.gradle.kts
- attribute-service-factory/build.gradle.kts
- attribute-service-impl/build.gradle.kts
- attribute-service/build.gradle.kts
- build.gradle.kts
- caching-attribute-service-client/build.gradle.kts
- owasp-suppressions.xml
Update CI workflows to
use newer runners
use latest action versions
remove redundant caching (now built into gradle actions)
remove redundant check in build job (moved all verification into test job which was already running tests)
replace snyk scan with owasp-based hypertrace action
Also updated certain libs to fix vulnerabilities.
> ci: update ci, vulns

- helm/Chart.yaml
Upgrades https://github.com/hypertrace/config-bootstrapper/pull/89
> chore: upgrade config bootstrapper

- attribute-service-api/build.gradle.kts
- attribute-service-client/build.gradle.kts
- attribute-service-factory/build.gradle.kts
- attribute-service-impl/build.gradle.kts
- attribute-service/build.gradle.kts
- caching-attribute-service-client/build.gradle.kts
- owasp-suppressions.xml
Update a couple dep versions due to grpc vulns
> refactor: update dependencies

- .github/actions/raise-lock-pr/action.yaml
- .github/workflows/update-locks.yml
- settings-gradle.lockfile
A bit of cleanup now that the cation can be tested. Moved checkout, removed redundant dirty check, added scheduling.
> ci: move checkout

- .github/workflows/update-locks.yml
Silly typo, swapped the repo name with action name.
> ci: fix typo

- .github/workflows/update-locks.yml
Update lock workflow to generate a token (which will allow it to trigger CI checks when raising PR)
> ci: generate token
