attribute-service/src/main/resources/configs/common/application.conf
- to differentiate it from a pool of services for common JVM metrics
=> adding metrics reporter prefix for the service

attribute-service/src/integrationTest/resources/configs/attribute-service/application.conf, attribute-service/src/main/resources/configs/common/application.conf
- convert an exposed mongo_host property to upper case to be consistent with other environ properties
=> provides a way to override the mongo_host via an environment variable

README.md, attribute-service-client/build.gradle.kts, attribute-service-impl/build.gradle.kts, attribute-service/build.gradle.kts
This PR
- Answers how Hypertrace uses attribute service
- Adds schematic representation for attribute service 
- Adds flows involving attribute service
- Add steps to build image locally
- link to dockerhub image source
=> adds illustrations to help understand attribute service and building steps

attribute-service-impl/build.gradle.kts, attribute-service/build.gradle.kts
Upgrading the docstore version to latest, which changes the mongo java driver used from 3.12 to 4.1.1. This is because the previous java driver is very old, marked legacy driver by MongoDB and there are a lot of bug fixes in the newer versions.
Most importantly, we are running into some issues with bulk upsert in production and we're trying to see if we see those same issues with the latest Mongo java driver too.
Ran Hypertrace locally with the locally built image and things are working fine.
No functionality is changed, hence no docs needed.
=> feat: Upgrading docstore version to upgrade mongo java driver.

attribute-projection-registry/src/main/java/org/hypertrace/core/attribute/service/projection/AttributeProjectionRegistry.java
The return type and first argument type were switched for CONDITIONAL and STRING_EQUALS. The return type is the first argument in the projection.
=> fix: switched return type and first argument type in projection registry

helm/templates/configmap.yaml
fix the qoute issue to supports url with a colon for document store configuration 
e.g "mongodb://mongo:27017"
HOCON treats `:` as a value separator (https://github.com/lightbend/config/blob/master/HOCON.md#key-value-separator), fixing the parsing error by quoting each value string.
Tried locally with - `helm template ./helm/` by adding above `url` values in values.yaml file.
e.g output:
```
application.conf: |-
document.store {
dataStoreType = mongo
mongo {
host = "mongo"
url = "mongodb://mongo:27017"
}
}
```
Not required
=> adding qoute for supporting colon in url

attribute-service/src/integrationTest/README.md
The current README for running the integration test locally mentions that before running the integration test, `Bring up a mongodb container locally using Docker or port forward to the mongo container in Kubernetes`. This step is actually not required. In fact, port forwarding while running the integration test may lead to modification of the shared database.
So, we need to update the README with the correct instructions.
=> Update README for running integration test locally

.github/workflows/merge-publish.yml, .github/workflows/pr-build.yml, .github/workflows/pr-test.yml, .github/workflows/publish.yml
- exposes docker env variables for gradle steps. 
- addresses Ronak's and Aaron's comments here: https://github.com/hypertrace/attribute-service/pull/45
https://github.com/hypertrace/hypertrace-gradle-docker-plugins/blob/c4cbaa615a03724c17c9eed0decf7311ac8128dc/hypertrace-gradle-docker-plugin/README.md#other-configuration
=> Exposes docker env variables to gradle steps

.github/CODEOWNERS, .github/workflows/pr-build.yml, .github/workflows/pr-test.yml, .github/workflows/publish.yml
- Avoids exposing secrets in `pr-build` which runs in `pull_request_target` context. 
- adds publish-images dependency for helm chart publish job. 
- Adds codeowners for github actions
=> avoids exposing env variables in pr-build

.github/workflows/pr-build.yml, .github/workflows/publish.yml
This fixes helm package step, by updating to a new package image which supports GHA (requires merge and release of https://github.com/hypertrace/helm-gcs-packager/pull/11)
=> ci: update to use new helm packager image

.github/workflows/publish.yml
updates required job name to `publish-artifacts` as it was changed earlier.
=> updates required job name for helm publish in GHA

.github/workflows/publish.yml
We are using `git describe --abbrev=0` for tagging charts but it's somehow is still on `0.8.7` and we are not able to release helm charts because of that. 
With this PR, we are using GITHUB_REF to get tag for helm charts as well which is standard practice.
=> switches to GITHUB_REF for tagging helm charts

.github/workflows/merge-publish.yml, .github/workflows/pr-build.yml, .github/workflows/pr-test.yml, .github/workflows/publish.yml
This PR uses new custom actions for 
- Gradle
- Validate charts and publish
changes as per discussions here: https://github.com/hypertrace/query-service/pull/47
tested changes here: https://github.com/hypertrace/attribute-service/pull/65
- https://github.com/hypertrace/actions/pull/9
=> uses new custom actions for GHA workflows

.snyk, attribute-service-impl/build.gradle.kts, attribute-service/build.gradle.kts
Updates doc-store version to include SQLi fix - hypertrace/document-store#30
=> chore: bump doc-store version to include SQLi fix

attribute-service-impl/build.gradle.kts, attribute-service/build.gradle.kts
Updates doc-store version to include postgres impl of exists, not-exists, and NEQ filters 
- https://github.com/hypertrace/document-store/pull/35
- https://github.com/hypertrace/document-store/pull/33
=> chore: bump doc-store version to include postgres impl of exits, not-exits and neq

attribute-service-api/src/main/proto/org/hypertrace/core/attribute/service/v1/attribute_metadata.proto
We previously allowed defining an attribute based on its string key, but certain fields in a span and trace are treated as first class and only accessible through those concrete fields. This change adds support to the attribute definition schema to access those values.
Schema change only (but used this functionality as part of an e2e verification)
- [N/A] I have added tests that prove my fix is effective or that my feature works
=> feat: add way of defining an attribute from first class field

attribute-service-api/src/main/proto/org/hypertrace/core/attribute/service/v1/attribute_metadata.proto, attribute-service/build.gradle.kts
This allows fallback support, where we can propose alternative definitions of an attribute that will be tried in order. For example, if we wanted to get the version of the tracer we could define an attribute with a definition like below, first trying the hypertrace version attribute, and if missing using the otel spec defined one. Changes to support evaluating this will be added to the attribute reader.
```
definition: {
first_value_present: {
definitions: [
{
source_path: hypertrace.module.version
},
{
source_path: telemetry.sdk.version
}
]
}
}
```
API addition only, but verified it functionally in an e2e setup.
=> feat: add attribute definition for fallback support

helm/Chart.yaml
Update to newer config bootstrapper which uses the newer attribute client (and thus supports new attribute definitions as added in `0.11.0`
=> chore: update config bootstrapper with new attr client

helm/Chart.yaml
Update config bootstrapper dependency with support for current attribute schema ( https://github.com/hypertrace/config-bootstrapper/pull/56 )
=> chore: update config bootstrapper

caching-attribute-service-client/build.gradle.kts, caching-attribute-service-client/src/main/java/org/hypertrace/core/attribute/service/cachingclient/DefaultCachingAttributeClient.java
Excessive error construction was eating up CPU cycles - changed to lazy construction, and added a throttled log message
=> chore: creating lazy errors

attribute-service-api/src/main/proto/org/hypertrace/core/attribute/service/v1/attribute_metadata.proto, attribute-service-impl/src/main/java/org/hypertrace/core/attribute/service/model/AttributeMetadataModel.java, attribute-service-impl/src/test/java/org/hypertrace/core/attribute/service/model/AttributeMetadataModelTest.java, attribute-service/src/integrationTest/java/org/hypertrace/core/attribute/service/AttributeServiceTest.java
This flag will tell whether the attribute is meant for internal use only or it can be used externally as well (i.e. can be exposed to the UI).
=> Internal flag in attribute_metadata

attribute-service-impl/src/main/java/org/hypertrace/core/attribute/service/AttributeServiceImpl.java
The previous implementation applied the internal attribute filter always, which works for newly written attributes but not for legacy attributes that are missing that key. This change adds backwards compatibility.
This only applies to legacy data so difficult to test without a pre-seeded DB. Verified manually against a legacy db.
=> fix: add backwards compatibility to internal filter

helm/Chart.yaml
See https://github.com/hypertrace/config-bootstrapper/pull/65
=> fix: bring in latest config to fix service name attribute

attribute-service-impl/build.gradle.kts, attribute-service/build.gradle.kts, caching-attribute-service-client/build.gradle.kts
Not known to be vulnerable in current config, but upgrading log4j due to https://nvd.nist.gov/vuln/detail/CVE-2021-45046 out of abundance of caution.
=> chore: update log4j

.github/workflows/pr-build.yml, attribute-service/build.gradle.kts
Please include a summary of the change, motivation and context.
added container scanning to attribute-service repo
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.
=> added container scanning to attribute-service repo

attribute-service-api/build.gradle.kts, attribute-service-factory/build.gradle.kts, attribute-service-impl/build.gradle.kts, attribute-service/build.gradle.kts
Fix vulnerabilities -
Testing /Users/kshitizsaxena/SourceCode/hypertrace/attribute-service...
Organization:      saxenakshitiz
Package manager:   gradle
Target file:       build.gradle.kts
Project name:      attribute-service
Open source:       no
Project path:      /Users/kshitizsaxena/SourceCode/hypertrace/attribute-service
Local Snyk policy: found
Licenses:          enabled
✔ Tested /Users/kshitizsaxena/SourceCode/hypertrace/attribute-service for known issues, no vulnerable paths found.
Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
-------------------------------------------------------
Testing /Users/kshitizsaxena/SourceCode/hypertrace/attribute-service...
Organization:      saxenakshitiz
Package manager: …
=> chore: fix vulnerabilities in attribute service

.github/workflows/codeql-analysis.yml, .github/workflows/pr-test.yml
Not sure why autobuild works and the hand build doesn't, but when compiling directly GH can't seem to find class files. The reason for the switch was to use the gradle action cache, so setting that up with a no-arg run beforehand now instead.
=> ci: restore autobuild for code scanning

attribute-service-impl/src/main/java/org/hypertrace/core/attribute/service/model/AttributeMetadataModel.java, attribute-service-impl/src/test/java/org/hypertrace/core/attribute/service/AttributeServiceImplTest.java, attribute-service-impl/src/test/java/org/hypertrace/core/attribute/service/delegate/AttributeUpdaterImplTest.java, attribute-service-impl/src/test/java/org/hypertrace/core/attribute/service/model/AttributeMetadataModelTest.java, attribute-service/src/integrationTest/java/org/hypertrace/core/attribute/service/AttributeServiceTest.java
Long standing bug where an empty attribute definition (the default) is assigned rather than leaving the field unset. This breaks presence detection downstream (i.e. `attribute.hasAttributeDefinition()`)
Added unit and integration test.
=> fix: attribute definition should be unset if default
